export const SITE_TITLE = "Anon's Blog";
export const SITE_DESCRIPTION = "はじめまして、千早愛音と申します。MyGO!!!!! ギター担当。";
export const SITE_URL = "https://besttianqi.github.io/AnonBlog";
export const BASE_PATH = "/AnonBlog";
export const POSTS_PER_PAGE = 3;
export const GISCUS_REPO = process.env.NEXT_PUBLIC_GISCUS_REPO || "";
export const GISCUS_REPO_ID = process.env.NEXT_PUBLIC_GISCUS_REPO_ID || "";
export const GISCUS_CATEGORY = process.env.NEXT_PUBLIC_GISCUS_CATEGORY || "";
export const GISCUS_CATEGORY_ID = process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID || "";
